services:
  backend:
    image: your-dockerhub-account/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      SECRET_KEY: my_secret_key_from_env
      DATABASE_URL: "postgresql://user:password@db-primary:5432/emails"
      FLASK_ENV: development
    depends_on:
      - db-primary
      - db-replica
    ports:
      - "5000:5000"

  db-primary:
    image: your-dockerhub-account/db-primary:latest
    build:
      context: ./db/primary
    volumes:
      - ./db/primary/data:/var/lib/postgresql/data
      - ./db/primary/postgresql.conf:/etc/postgresql-custom/postgresql.conf
      - ./db/primary/pg_hba.conf:/etc/postgresql-custom/pg_hba.conf
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emails
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql-custom/postgresql.conf"

  db-replica:
    image: your-dockerhub-account/db-replica:latest
    build:
      context: ./db/replica
    volumes:
      - ./db/replica/data:/var/lib/postgresql/data
      - ./db/replica/postgresql.conf:/etc/postgresql-custom/postgresql.conf
      - ./db/replica/pg_hba.conf:/etc/postgresql-custom/pg_hba.conf
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emails
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql-custom/postgresql.conf"

  frontend:
    image: your-dockerhub-account/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/static:/usr/share/nginx/html/static
    ports:
      - "80:80"
    depends_on:
      - backend

  load_balancer:
    image: your-dockerhub-account/load-balancer:latest
    build:
      context: ./load_balancer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
